Run collectstatic at container startup and simplify CI/CD

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,103 +1,94 @@
-﻿name: TSU PostHub API CI/CD
+﻿  name: TSU PostHub API CI/CD
+  
+  on:
+    push:
+      branches: [main]
+  
+  env:
+    DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/tsu-posthub-api
+    DEPLOY_USERNAME: 'deployuser'
+  
+  jobs:
+    build-and-deploy:
+      runs-on: ubuntu-latest
+      environment: Production
+      
+      steps:
+        - name: 📥 Checkout repository
+          uses: actions/checkout@v4
 
-on:
-  push:
-    branches: [main]
+        - name: 🐍 Setup Python
+          uses: actions/setup-python@v4
+          with:
+            python-version: 3.12
 
-env:
-  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/tsu-posthub-api
-  DEPLOY_USERNAME: 'deployuser'
+        - name: 📦 Install Poetry
+          run: pip install poetry
 
-jobs:
-  build-and-push:
-    runs-on: ubuntu-latest
-    environment: Production
+        - name: 📦 Install dependencies
+          run: poetry install --no-interaction --no-ansi
 
-    steps:
-      - name: 📥 Checkout repository
-        uses: actions/checkout@v4
+        - name: 🔐 Login to Docker Hub
+          uses: docker/login-action@v3
+          with:
+            username: ${{ secrets.DOCKER_USERNAME }}
+            password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: 🐍 Setup Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: 3.12
-
-      - name: 📦 Install Poetry
-        run: pip install poetry
-
-      - name: 📦 Install dependencies
-        run: poetry install --no-interaction --no-ansi
-
-      - name: 🔐 Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-
-      - name: 🐳 Build and Push Docker image
-        uses: docker/build-push-action@v5
-        with:
-          context: .
-          file: ./Dockerfile
-          push: true
-          tags: |
-            ${{ env.DOCKER_IMAGE }}:latest
-            ${{ env.DOCKER_IMAGE }}:${{ github.run_number }}
-
-  deploy-and-collectstatic:
-    runs-on: ubuntu-latest
-    needs: build-and-push
-    environment: Production
-
-    steps:
-      - name: 🚀 Deploy to Server (SSH)
-        uses: appleboy/ssh-action@v1.0.3
-        with:
-          host: ${{ secrets.SSH_HOST }}
-          username: ${{ env.DEPLOY_USERNAME }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          script: |
-            set -e
-
-            echo "📦 Backup previous container..."
-            docker tag tsu-posthub-api tsu-posthub-api-backup || true
-
-            echo "📥 Pull last image..."
-            docker pull ${{ env.DOCKER_IMAGE }}:latest
-
-            echo "🛑 Stop and remove current container..."
-            docker stop tsu-posthub-api || true
-            docker rm tsu-posthub-api || true
-
-            echo "🚀 Launch new container with media/static volumes and env file..."
-            docker run -d \
-              --name tsu-posthub-api \
-              -p 8000:8000 \
-              --env-file /home/${{ env.DEPLOY_USERNAME }}/tsu-posthub.env \
-              --network ${{ env.DEPLOY_USERNAME }}_tsu-eventhub_net \
-              -v /home/${{ env.DEPLOY_USERNAME }}/static:/vol/web/static \
-              -v /home/${{ env.DEPLOY_USERNAME }}/media:/vol/web/media \
+        - name: 🐳 Build and Push Docker image
+          uses: docker/build-push-action@v5
+          with:
+            context: .
+            file: ./Dockerfile
+            push: true
+            tags: |
               ${{ env.DOCKER_IMAGE }}:latest
+              ${{ env.DOCKER_IMAGE }}:${{ github.run_number }}
 
-            echo "🗂 Running collectstatic..."
-            docker exec tsu-posthub-api python manage.py collectstatic --noinput --clear
+        - name: 🚀 Deploy to Server (SSH)
+          uses: appleboy/ssh-action@v1.0.3
+          with:
+            host: ${{ secrets.SSH_HOST }}
+            username: ${{ env.DEPLOY_USERNAME }}
+            key: ${{ secrets.SSH_PRIVATE_KEY }}
+            script: |
+              set -e
+              
+              echo "📦 Backup previous container..."
+              docker tag tsu-posthub-api tsu-posthub-api-backup || true
+              
+              echo "📥 Pull last image..."
+              docker pull ${{ env.DOCKER_IMAGE }}:latest
+              
+              echo "🛑 Stop and remove current container..."
+              docker stop tsu-posthub-api || true
+              docker rm tsu-posthub-api || true
+              
+              echo "🚀 Launch new container with media volume and env file..."
+              docker run -d \
+                --name tsu-posthub-api \
+                -p 8000:8000 \
+                --env-file /home/${{ env.DEPLOY_USERNAME }}/tsu-posthub.env \
+                --network ${{ env.DEPLOY_USERNAME }}_tsu-eventhub_net \
+                -v /home/${{ env.DEPLOY_USERNAME }}/static:/vol/web/static \
+                -v /home/${{ env.DEPLOY_USERNAME }}/media:/vol/web/media \
+                ${{ env.DOCKER_IMAGE }}:latest
 
-      - name: 🛠 Rollback
-        if: failure()
-        uses: appleboy/ssh-action@v1.0.3
-        with:
-          host: ${{ secrets.SSH_HOST }}
-          username: ${{ env.DEPLOY_USERNAME }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          script: |
-            echo "⚠️ Deployment error. Rollback to previous container..."
-            docker stop tsu-posthub-api || true
-            docker rm tsu-posthub-api || true
-            docker run -d \
-              --name tsu-posthub-api \
-              -p 8000:8000 \
-              --env-file /home/${{ env.DEPLOY_USERNAME }}/tsu-posthub.env \
-              --network ${{ env.DEPLOY_USERNAME }}_tsu-eventhub_net \
-              -v /home/${{ env.DEPLOY_USERNAME }}/static:/vol/web/static \
-              -v /home/${{ env.DEPLOY_USERNAME }}/media:/vol/web/media \
-              tsu-posthub-api-backup
+        - name: 🛠 Rollback
+          if: failure()
+          uses: appleboy/ssh-action@v1.0.3
+          with:
+            host: ${{ secrets.SSH_HOST }}
+            username: ${{ env.DEPLOY_USERNAME }}
+            key: ${{ secrets.SSH_PRIVATE_KEY }}
+            script: |
+              echo "⚠️ Deployment error. Rollback to previous container..."
+              docker stop tsu-posthub-api || true
+              docker rm tsu-posthub-api || true
+              docker run -d \
+                --name tsu-posthub-api \
+                -p 8000:8000 \
+                --env-file /home/${{ env.DEPLOY_USERNAME }}/tsu-posthub.env \
+                --network ${{ env.DEPLOY_USERNAME }}_tsu-eventhub_net \
+                -v /home/${{ env.DEPLOY_USERNAME }}/static:/vol/web/static \
+                -v /home/${{ env.DEPLOY_USERNAME }}/media:/vol/web/media \
+                tsu-posthub-api-backup
